version: 1
project:
  name: cupuacu
  vault:
    connection: home-vault
    secrets:
      - name: github-secret
        mount: kv
        path: gh
        key: token
        kv_version: 2

pipelines:
  - id: build
    trigger: manual
    source:
      repo: https://github.com/izzyreal/cupuacu.git
    versioning:
      file: VERSION
      tag_prefix: v
    jobs:
      - id: linux-amd64
        runs_on:
          executor: script
          shell: posix
          os: linux
          arch: amd64
        requires:
          tools:
            git: "*"
            cmake: "*"
          capabilities:
            xorg-dev: "1"
        timeout_seconds: 1800
        artifacts:
          - dist/**
        caches: &fetchcontent_caches
          - id: fetchcontent
            env: FETCHCONTENT_BASE_DIR
            key:
              prefix: fetchcontent-v1
              files:
                - CMakeLists.txt
                - cmake/**/*.cmake
              runtime:
                - os
                - arch
              tools:
                - cmake
              env:
                - CC
                - CXX
                - CMAKE_TOOLCHAIN_FILE
            policy: pull-push
            ttl_days: 14
            max_size_mb: 20480
        steps:
          - run: mkdir -p build/linux-amd64 dist
          - run: cmake -S . -B build/linux-amd64 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFETCHCONTENT_BASE_DIR="$FETCHCONTENT_BASE_DIR"
          - run: cmake --build build/linux-amd64 --config Release --target Cupuacu cupuacu-tests
          - test:
              name: cupuacu-tests
              command: ./build/linux-amd64/cupuacu-tests --reporter JUnit --out build/linux-amd64/result-junit.xml
              format: junit-xml
              report: build/linux-amd64/result-junit.xml
          - run: cp build/linux-amd64/Cupuacu dist/cupuacu-linux-amd64
          - run: cp build/linux-amd64/cupuacu-tests dist/cupuacu-tests-linux-amd64

      - id: macos-universal
        runs_on:
          executor: script
          shell: posix
          os: darwin
          arch: arm64
        requires:
          tools:
            git: "*"
            cmake: "*"
        timeout_seconds: 1800
        artifacts:
          - dist/**
        caches: *fetchcontent_caches
        steps:
          - run: mkdir -p build/macos-universal dist
          - run: cmake -S . -B build/macos-universal -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DFETCHCONTENT_BASE_DIR="$FETCHCONTENT_BASE_DIR"
          - run: cmake --build build/macos-universal --config Release --target Cupuacu cupuacu-tests
          - test:
              name: cupuacu-tests
              command: ./build/macos-universal/cupuacu-tests --reporter JUnit --out build/macos-universal/result-junit.xml
              format: junit-xml
              report: build/macos-universal/result-junit.xml
          - run: cp build/macos-universal/Cupuacu dist/cupuacu-macos-universal
          - run: cp build/macos-universal/cupuacu-tests dist/cupuacu-tests-macos-universal

      - id: windows-amd64
        runs_on:
          executor: script
          shell: cmd
          os: windows
          arch: amd64
        requires:
          tools:
            git: "*"
            cmake: "*"
        timeout_seconds: 1800
        artifacts:
          - dist/**
        caches: *fetchcontent_caches
        steps:
          - run: if not exist build\windows-amd64 mkdir build\windows-amd64
          - run: if not exist dist mkdir dist
          - run: cmake -S . -B build\windows-amd64 -G "Visual Studio 18 2026" -A x64 -DFETCHCONTENT_BASE_DIR="%FETCHCONTENT_BASE_DIR%"
          - run: cmake --build build\windows-amd64 --config Release --target Cupuacu cupuacu-tests
          - test:
              name: cupuacu-tests
              command: build\windows-amd64\Release\cupuacu-tests.exe --reporter JUnit --out build\windows-amd64\result-junit.xml
              format: junit-xml
              report: build/windows-amd64/result-junit.xml
          - run: copy /Y build\windows-amd64\Release\Cupuacu.exe dist\cupuacu-windows-amd64.exe
          - run: copy /Y build\windows-amd64\Release\cupuacu-tests.exe dist\cupuacu-tests-windows-amd64.exe

  - id: release
    trigger: manual
    depends_on:
      - build
    source:
      repo: https://github.com/izzyreal/cupuacu.git
    versioning:
      file: VERSION
      tag_prefix: v
    jobs:
      - id: github-release
        runs_on:
          executor: script
          shell: posix
          os: linux
          arch: amd64
        requires:
          tools:
            git: "*"
            gh: "*"
        timeout_seconds: 2400
        steps:
          - run: test -n "$GITHUB_TOKEN"
            env:
              GITHUB_TOKEN: "{{ secret.github-secret }}"
            skip_dry_run: true
          - run: test -f VERSION
          - run: test -f dist/cupuacu-linux-amd64
          - run: test -f dist/cupuacu-macos-universal
          - run: test -f dist/cupuacu-windows-amd64.exe
          - run: |
              shasum -a 256 \
                dist/cupuacu-linux-amd64 \
                dist/cupuacu-macos-universal \
                dist/cupuacu-windows-amd64.exe \
                > dist/cupuacu-checksums.txt
          - run: |
              TAG="${CIWI_PIPELINE_TAG}"
              git config user.name "ciwi-agent"
              git config user.email "ciwi-agent@local"
              git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/izzyreal/cupuacu.git"
            env:
              GITHUB_TOKEN: "{{ secret.github-secret }}"
            skip_dry_run: true
          - run: |
              TAG="${CIWI_PIPELINE_TAG}"
              if ! git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
                git tag -a "$TAG" -m "cupuacu $TAG"
                git push origin "$TAG"
              fi
            skip_dry_run: true
          - run: |
              TAG="${CIWI_PIPELINE_TAG}"
              if ! gh release view "$TAG" --repo izzyreal/cupuacu >/dev/null 2>&1; then
                gh release create "$TAG" \
                  --repo izzyreal/cupuacu \
                  --title "cupuacu $TAG" \
                  --notes "Release $TAG"
              fi
              gh release upload "$TAG" \
                dist/cupuacu-linux-amd64 \
                dist/cupuacu-macos-universal \
                dist/cupuacu-windows-amd64.exe \
                dist/cupuacu-checksums.txt \
                --repo izzyreal/cupuacu \
                --clobber
            skip_dry_run: true
            env:
              GITHUB_TOKEN: "{{ secret.github-secret }}"

pipeline_chains:
  - id: build-release
    pipelines:
      - build
      - release
