file(GLOB_RECURSE _sources RELATIVE "${SOURCE_ROOT}"
    "${SOURCE_ROOT}/src/main/*" "${SOURCE_ROOT}/src/benchmark/*"
    "${SOURCE_ROOT}/cmake/*.cmake" "${SOURCE_ROOT}/cmake/*.in")
list(APPEND _sources "CMakeLists.txt" "scripts/run-benchmarks.py")
list(SORT _sources)
set(_input "")
foreach(_source IN LISTS _sources)
    if(NOT IS_DIRECTORY "${SOURCE_ROOT}/${_source}")
        file(SHA256 "${SOURCE_ROOT}/${_source}" _hash)
        string(APPEND _input "${_source}:${_hash}\n")
    endif()
endforeach()
string(SHA256 _hash "${_input}")
set(_content "#pragma once\ninline constexpr auto benchmarkSourceFingerprint = \"${_hash}\";\n")
set(_previous "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _previous)
endif()
if(NOT _content STREQUAL _previous)
    file(WRITE "${OUTPUT}" "${_content}")
endif()
